@baseUrl = http://localhost:8000

###
# Get root message
GET {{baseUrl}}/
Accept: application/json

###
# Get an item by ID with optional query
GET {{baseUrl}}/items/42?q=skippy
Accept: application/json

###
# Get sample training plan by full ID
GET {{baseUrl}}/plans/2b12a982-a223-4e52-baa5-51d4e5c321e8
Accept: application/json